# Generated by Django 3.1.5 on 2021-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=100)),
                ('pizza_size', models.CharField(max_length=100)),
                ('topping_type', models.CharField(max_length=100)),
            ],
        ),
    ]
