# Generated by Django 3.1.5 on 2021-03-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='toppingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pizzasizemodel')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pizzatypemodel')),
                ('topping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.toppingmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
    ]
