# Generated by Django 3.1.5 on 2021-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210325_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=100)),
                ('pizza_size', models.CharField(max_length=100)),
                ('topping_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pizza_size',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pizza_type',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='topping_type',
        ),
        migrations.DeleteModel(
            name='PizzaSizeModel',
        ),
        migrations.DeleteModel(
            name='PizzaTypeModel',
        ),
        migrations.DeleteModel(
            name='toppingModel',
        ),
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
